name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit & Widget Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"
      - run: flutter test test/ || echo "Unit tests not found"
      - run: flutter test test/widget_test.dart || echo "Widget tests not found"

  android_instrumentation_tests:
    name: Android Integration Tests
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4

      - name: Setup KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm
          sudo chown $USER /dev/kvm
          sudo chmod 666 /dev/kvm

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"

      - name: Install Android Emulator
        run: |
          sdkmanager "system-images;android-29;google_apis;x86_64"
          sdkmanager "platform-tools" "emulator"
          echo "y" | avdmanager create avd \
            -n test \
            -k "system-images;android-29;google_apis;x86_64" \
            -d "Nexus 6"

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            echo "=== Starting emulator ==="
            flutter emulators
            adb devices

            echo "=== Waiting for device ==="
            adb wait-for-device
            while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 5; done

            echo "=== Unlocking device ==="
            adb shell input keyevent 82

  packaging:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [tests, android_instrumentation_tests]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
