name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit & Widget Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"
      - run: flutter test test/ || echo "Unit tests not found"
      - run: flutter test test/widget_test.dart || echo "Widget tests not found"

  android_instrumentation_tests:
    name: Android Integration Tests
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4

      - name: Setup KVM
        run: |
          sudo chmod 666 /dev/kvm
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          script: |
            echo "=== Starting emulator setup ==="
            flutter devices
            adb wait-for-device
            echo "Waiting for device to fully boot..."
            sleep 60
            adb shell input keyevent 82

            echo "=== Checking for integration tests ==="
            if [ -f "integration_test/app_test.dart" ]; then
              echo "Running integration tests..."
              flutter drive \
                --driver=test_driver/integration_test.dart \
                --target=integration_test/app_test.dart \
                --device-timeout 5m
            else
              echo "No integration tests found at integration_test/app_test.dart"
            fi

            echo "=== Test execution completed ==="
            adb devices
            adb logcat -d

  packaging:
    name: Build and Package
    runs-on: ubuntu-latest
    needs: [tests, android_instrumentation_tests]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
